# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0005_auto_20180409_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newblogs',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='myapps.User_registration'),
        ),
    ]
