# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0006_auto_20180409_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newblogs',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
