# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0008_auto_20180410_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='myapps.Users'),
        ),
    ]
