# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0010_auto_20180410_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(max_length=5)),
                ('bid', models.IntegerField(max_length=5)),
            ],
        ),
    ]
